INSERT OVERWRITE TABLE CDS_MAIN_ORDERS
SELECT
    S.ORDER_ID,
    S.CLIENT_ID,
    C.CLIENT_NAME,
    C.CLIENT_TYPE,
    S.SECURITY_ID,
    M.SECURITY_NAME,
    M.SECURITY_TYPE,
    M.EXCHANGE,
    S.TRADE_DATE,
    D.MONTH,
    D.QUARTER,
    D.YEAR,
    S.ORDER_TYPE,
    S.BUY_SELL_IND,
    S.QUANTITY,
    S.PRICE,
    S.GROSS_AMOUNT,
    S.STANDARD_STATUS,
    CASE WHEN S.GROSS_AMOUNT >= 10000000 THEN 'HIGH' WHEN S.GROSS_AMOUNT >= 1000000 THEN 'MEDIUM' ELSE 'LOW' END AS ORDER_RISK_BUCKET,
    CURRENT_TIMESTAMP AS MAIN_LOAD_TIMESTAMP
FROM CDS_S2_ORDER_STAGE S
JOIN DIM_CLIENT_MASTER C ON S.CLIENT_ID = C.CLIENT_ID
JOIN DIM_SECURITY_MASTER M ON S.SECURITY_ID = M.SECURITY_ID
JOIN DIM_DMO_CALENDAR D ON S.TRADE_DATE = D.BUSINESS_DATE
WHERE S.STANDARD_STATUS = 'EXECUTED'
  AND C.CLIENT_STATUS = 'ACTIVE'
  AND D.IS_BUSINESS_DAY = 'Y';
