INSERT OVERWRITE TABLE DENORM_CUSTOMER_HOLDINGS
SELECT
    O.CLIENT_ID,
    C.CLIENT_NAME,
    C.CLIENT_TYPE,
    O.SECURITY_ID,
    O.TRADE_DATE AS HOLDING_DATE,
    SUM(CASE WHEN O.BUY_SELL_IND = 'BUY' THEN O.QUANTITY ELSE -1 * O.QUANTITY END) AS HOLDING_QUANTITY,
    SUM(CASE WHEN O.BUY_SELL_IND = 'BUY' THEN O.GROSS_AMOUNT ELSE -1 * O.GROSS_AMOUNT END) AS HOLDING_VALUE,
    CURRENT_TIMESTAMP AS REPORT_LOAD_TIMESTAMP
FROM CM_MAIN_ORDERS O
JOIN DIM_CLIENT_MASTER C ON O.CLIENT_ID = C.CLIENT_ID
GROUP BY O.CLIENT_ID, C.CLIENT_NAME, C.CLIENT_TYPE, O.SECURITY_ID, O.TRADE_DATE;
