INSERT OVERWRITE TABLE DENORM_CLIENT_POSITION
SELECT
    O.CLIENT_ID,
    C.CLIENT_NAME,
    C.CLIENT_TYPE,
    O.TRADE_DATE AS POSITION_DATE,
    COUNT(*) AS ORDER_COUNT,
    SUM(O.QUANTITY) AS TOTAL_QUANTITY,
    SUM(O.GROSS_AMOUNT) AS TOTAL_GROSS_AMOUNT,
    CURRENT_TIMESTAMP AS REPORT_LOAD_TIMESTAMP
FROM FAO_MAIN_ORDERS O
JOIN DIM_CLIENT_MASTER C ON O.CLIENT_ID = C.CLIENT_ID
GROUP BY O.CLIENT_ID, C.CLIENT_NAME, C.CLIENT_TYPE, O.TRADE_DATE;
