CREATE TABLE IF NOT EXISTS DIM_CLIENT_MASTER (
    CLIENT_ID VARCHAR(40) NOT NULL,
    CLIENT_NAME VARCHAR(200),
    CLIENT_TYPE VARCHAR(40),
    COUNTRY VARCHAR(80),
    CLIENT_STATUS VARCHAR(20),
    EFFECTIVE_DATE DATE,
    LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DIM_SECURITY_MASTER (
    SECURITY_ID VARCHAR(40) NOT NULL,
    SECURITY_NAME VARCHAR(200),
    SECURITY_TYPE VARCHAR(40),
    EXCHANGE VARCHAR(20),
    CURRENCY_CODE VARCHAR(3),
    LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DIM_DMO_CALENDAR (
    BUSINESS_DATE DATE NOT NULL,
    MONTH INT,
    QUARTER INT,
    YEAR INT,
    IS_BUSINESS_DAY CHAR(1),
    LOAD_TIMESTAMP TIMESTAMP
);
