CREATE TABLE IF NOT EXISTS FAO_S2_ORDER_STAGE (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40) NOT NULL,
    SECURITY_ID VARCHAR(40) NOT NULL,
    TRADE_DATE DATE NOT NULL,
    ORDER_TYPE VARCHAR(20),
    BUY_SELL_IND VARCHAR(4),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    GROSS_AMOUNT DECIMAL(20, 4),
    STANDARD_STATUS VARCHAR(20),
    SOURCE_SYSTEM VARCHAR(40),
    LOAD_TIMESTAMP TIMESTAMP,
    STAGE_LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CM_S2_ORDER_STAGE (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40) NOT NULL,
    SECURITY_ID VARCHAR(40) NOT NULL,
    TRADE_DATE DATE NOT NULL,
    ORDER_TYPE VARCHAR(20),
    BUY_SELL_IND VARCHAR(4),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    GROSS_AMOUNT DECIMAL(20, 4),
    STANDARD_STATUS VARCHAR(20),
    SOURCE_SYSTEM VARCHAR(40),
    LOAD_TIMESTAMP TIMESTAMP,
    STAGE_LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CDS_S2_ORDER_STAGE (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40) NOT NULL,
    SECURITY_ID VARCHAR(40) NOT NULL,
    TRADE_DATE DATE NOT NULL,
    ORDER_TYPE VARCHAR(20),
    BUY_SELL_IND VARCHAR(4),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    GROSS_AMOUNT DECIMAL(20, 4),
    STANDARD_STATUS VARCHAR(20),
    SOURCE_SYSTEM VARCHAR(40),
    LOAD_TIMESTAMP TIMESTAMP,
    STAGE_LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COM_S2_ORDER_STAGE (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40) NOT NULL,
    SECURITY_ID VARCHAR(40) NOT NULL,
    TRADE_DATE DATE NOT NULL,
    ORDER_TYPE VARCHAR(20),
    BUY_SELL_IND VARCHAR(4),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    GROSS_AMOUNT DECIMAL(20, 4),
    STANDARD_STATUS VARCHAR(20),
    SOURCE_SYSTEM VARCHAR(40),
    LOAD_TIMESTAMP TIMESTAMP,
    STAGE_LOAD_TIMESTAMP TIMESTAMP
);
