INSERT OVERWRITE TABLE CDS_S2_ORDER_STAGE
SELECT
    ORDER_ID,
    CLIENT_ID,
    SECURITY_ID,
    TRADE_DATE,
    UPPER(TRIM(ORDER_TYPE)) AS ORDER_TYPE,
    CASE WHEN UPPER(TRIM(ORDER_TYPE)) IN ('BUY', 'B') THEN 'BUY' ELSE 'SELL' END AS BUY_SELL_IND,
    QUANTITY,
    PRICE,
    COALESCE(AMOUNT, QUANTITY * PRICE) AS GROSS_AMOUNT,
    CASE
        WHEN UPPER(TRIM(STATUS)) IN ('EXECUTED', 'FILLED', 'COMPLETE') THEN 'EXECUTED'
        WHEN UPPER(TRIM(STATUS)) IN ('CANCELLED', 'CANCELED', 'REJECTED') THEN 'CANCELLED'
        ELSE 'PENDING'
    END AS STANDARD_STATUS,
    SOURCE_SYSTEM,
    LOAD_TIMESTAMP,
    CURRENT_TIMESTAMP AS STAGE_LOAD_TIMESTAMP
FROM CDS_S1_RAW_ORDERS
WHERE ORDER_ID IS NOT NULL
  AND CLIENT_ID IS NOT NULL
  AND SECURITY_ID IS NOT NULL
  AND TRADE_DATE IS NOT NULL
  AND QUANTITY > 0
  AND PRICE >= 0
  AND SOURCE_SYSTEM = 'TRADING_PLATFORM';
