INSERT OVERWRITE TABLE DIM_CLIENT_MASTER
SELECT 'CLT10001', 'Apex Capital Partners', 'INSTITUTIONAL', 'INDIA', 'ACTIVE', CURRENT_DATE, CURRENT_TIMESTAMP
UNION ALL SELECT 'CLT10002', 'Northbridge Securities', 'BROKER', 'INDIA', 'ACTIVE', CURRENT_DATE, CURRENT_TIMESTAMP
UNION ALL SELECT 'CLT10003', 'Westlake Asset Management', 'FUND', 'SINGAPORE', 'ACTIVE', CURRENT_DATE, CURRENT_TIMESTAMP
UNION ALL SELECT 'CLT10004', 'Harbor Retail Investments', 'RETAIL', 'INDIA', 'ACTIVE', CURRENT_DATE, CURRENT_TIMESTAMP;
