INSERT OVERWRITE TABLE DIM_DMO_CALENDAR
SELECT BUSINESS_DATE,
       MONTH(BUSINESS_DATE) AS MONTH,
       QUARTER(BUSINESS_DATE) AS QUARTER,
       YEAR(BUSINESS_DATE) AS YEAR,
       CASE WHEN DAYOFWEEK(BUSINESS_DATE) IN (1, 7) THEN 'N' ELSE 'Y' END AS IS_BUSINESS_DAY,
       CURRENT_TIMESTAMP AS LOAD_TIMESTAMP
FROM (
    SELECT DATE '2026-06-10' AS BUSINESS_DATE
    UNION ALL SELECT DATE '2026-06-11'
    UNION ALL SELECT DATE '2026-06-12'
    UNION ALL SELECT DATE '2026-06-15'
) CAL;
