INSERT OVERWRITE TABLE DIM_SECURITY_MASTER
SELECT 'SEC_EQ_500112', 'State Bank Equity', 'EQUITY', 'NSE', 'INR', CURRENT_TIMESTAMP
UNION ALL SELECT 'SEC_FUT_NIFTY', 'Nifty Index Future', 'FUTURE', 'NFO', 'INR', CURRENT_TIMESTAMP
UNION ALL SELECT 'SEC_CDS_USDINR', 'USD INR Currency Future', 'CURRENCY', 'CDS', 'INR', CURRENT_TIMESTAMP
UNION ALL SELECT 'SEC_COM_GOLD', 'Gold Commodity Future', 'COMMODITY', 'MCX', 'INR', CURRENT_TIMESTAMP;
