CREATE TABLE IF NOT EXISTS FAO_S1_RAW_ORDERS (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40),
    SECURITY_ID VARCHAR(40),
    TRADE_DATE DATE,
    ORDER_TYPE VARCHAR(20),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    AMOUNT DECIMAL(20, 4),
    STATUS VARCHAR(30),
    SOURCE_SYSTEM VARCHAR(40),
    LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CM_S1_RAW_ORDERS (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40),
    SECURITY_ID VARCHAR(40),
    TRADE_DATE DATE,
    ORDER_TYPE VARCHAR(20),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    AMOUNT DECIMAL(20, 4),
    STATUS VARCHAR(30),
    SOURCE_SYSTEM VARCHAR(40),
    LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CDS_S1_RAW_ORDERS (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40),
    SECURITY_ID VARCHAR(40),
    TRADE_DATE DATE,
    ORDER_TYPE VARCHAR(20),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    AMOUNT DECIMAL(20, 4),
    STATUS VARCHAR(30),
    SOURCE_SYSTEM VARCHAR(40),
    LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COM_S1_RAW_ORDERS (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40),
    SECURITY_ID VARCHAR(40),
    TRADE_DATE DATE,
    ORDER_TYPE VARCHAR(20),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    AMOUNT DECIMAL(20, 4),
    STATUS VARCHAR(30),
    SOURCE_SYSTEM VARCHAR(40),
    LOAD_TIMESTAMP TIMESTAMP
);
