CREATE TABLE IF NOT EXISTS FAO_TRADE_FACT (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40) NOT NULL,
    CLIENT_TYPE VARCHAR(40),
    SECURITY_ID VARCHAR(40) NOT NULL,
    SECURITY_TYPE VARCHAR(40),
    TRADE_DATE DATE NOT NULL,
    YEAR INT,
    MONTH INT,
    ORDER_TYPE VARCHAR(20),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    TRADE_VALUE DECIMAL(20, 4),
    BROKERAGE_AMOUNT DECIMAL(20, 4),
    NET_AMOUNT DECIMAL(20, 4),
    FACT_LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CM_TRADE_FACT (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40) NOT NULL,
    CLIENT_TYPE VARCHAR(40),
    SECURITY_ID VARCHAR(40) NOT NULL,
    SECURITY_TYPE VARCHAR(40),
    TRADE_DATE DATE NOT NULL,
    YEAR INT,
    MONTH INT,
    ORDER_TYPE VARCHAR(20),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    TRADE_VALUE DECIMAL(20, 4),
    BROKERAGE_AMOUNT DECIMAL(20, 4),
    NET_AMOUNT DECIMAL(20, 4),
    FACT_LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CDS_TRADE_FACT (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40) NOT NULL,
    CLIENT_TYPE VARCHAR(40),
    SECURITY_ID VARCHAR(40) NOT NULL,
    SECURITY_TYPE VARCHAR(40),
    TRADE_DATE DATE NOT NULL,
    YEAR INT,
    MONTH INT,
    ORDER_TYPE VARCHAR(20),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    TRADE_VALUE DECIMAL(20, 4),
    BROKERAGE_AMOUNT DECIMAL(20, 4),
    NET_AMOUNT DECIMAL(20, 4),
    FACT_LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COM_TRADE_FACT (
    ORDER_ID VARCHAR(40) NOT NULL,
    CLIENT_ID VARCHAR(40) NOT NULL,
    CLIENT_TYPE VARCHAR(40),
    SECURITY_ID VARCHAR(40) NOT NULL,
    SECURITY_TYPE VARCHAR(40),
    TRADE_DATE DATE NOT NULL,
    YEAR INT,
    MONTH INT,
    ORDER_TYPE VARCHAR(20),
    QUANTITY DECIMAL(18, 4),
    PRICE DECIMAL(18, 6),
    TRADE_VALUE DECIMAL(20, 4),
    BROKERAGE_AMOUNT DECIMAL(20, 4),
    NET_AMOUNT DECIMAL(20, 4),
    FACT_LOAD_TIMESTAMP TIMESTAMP
);
