CREATE TABLE IF NOT EXISTS DENORM_CLIENT_POSITION (
    CLIENT_ID VARCHAR(40) NOT NULL,
    CLIENT_NAME VARCHAR(200),
    CLIENT_TYPE VARCHAR(40),
    POSITION_DATE DATE NOT NULL,
    ORDER_COUNT BIGINT,
    TOTAL_QUANTITY DECIMAL(20, 4),
    TOTAL_GROSS_AMOUNT DECIMAL(22, 4),
    REPORT_LOAD_TIMESTAMP TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DENORM_CUSTOMER_HOLDINGS (
    CLIENT_ID VARCHAR(40) NOT NULL,
    CLIENT_NAME VARCHAR(200),
    CLIENT_TYPE VARCHAR(40),
    SECURITY_ID VARCHAR(40) NOT NULL,
    HOLDING_DATE DATE NOT NULL,
    HOLDING_QUANTITY DECIMAL(20, 4),
    HOLDING_VALUE DECIMAL(22, 4),
    REPORT_LOAD_TIMESTAMP TIMESTAMP
);
