INSERT OVERWRITE TABLE CM_TRADE_FACT
SELECT
    R.ORDER_ID,
    R.CLIENT_ID,
    C.CLIENT_TYPE,
    R.SECURITY_ID,
    M.SECURITY_TYPE,
    R.TRADE_DATE,
    D.YEAR,
    D.MONTH,
    UPPER(TRIM(R.ORDER_TYPE)) AS ORDER_TYPE,
    R.QUANTITY,
    R.PRICE,
    R.QUANTITY * R.PRICE AS TRADE_VALUE,
    (R.QUANTITY * R.PRICE) * 0.0004 AS BROKERAGE_AMOUNT,
    CASE WHEN UPPER(TRIM(R.ORDER_TYPE)) IN ('BUY', 'B')
         THEN (R.QUANTITY * R.PRICE) + ((R.QUANTITY * R.PRICE) * 0.0004)
         ELSE (R.QUANTITY * R.PRICE) - ((R.QUANTITY * R.PRICE) * 0.0004)
    END AS NET_AMOUNT,
    CURRENT_TIMESTAMP AS FACT_LOAD_TIMESTAMP
FROM CM_S1_RAW_ORDERS R
JOIN DIM_CLIENT_MASTER C ON R.CLIENT_ID = C.CLIENT_ID
JOIN DIM_SECURITY_MASTER M ON R.SECURITY_ID = M.SECURITY_ID
JOIN DIM_DMO_CALENDAR D ON R.TRADE_DATE = D.BUSINESS_DATE
WHERE R.SOURCE_SYSTEM = 'TRADING_PLATFORM'
  AND R.STATUS IN ('EXECUTED', 'FILLED', 'COMPLETE');
